#Spring Boot 会自动扫描classpath下的application.yml文件，如果有就加载文件配置


########################################################################################
#Spring Boot中多环境配置文件名需要满足application-{profile}.yml的格式
#{profile}对应你的环境标识
#application-dev.yml：开发环境
#application-test.yml：测试环境
#application-prod.yml：生产环境
# 多环境配置文件激活属性---开发、测试、生产spring:
spring:
  profiles:
    active: dev